In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("spotify_songs.csv")

In [3]:
# df.info()

In [4]:
df.columns

Index(['track_id', 'track_name', 'track_artist', 'track_popularity',
       'track_album_id', 'track_album_name', 'track_album_release_date',
       'playlist_name', 'playlist_id', 'playlist_genre', 'playlist_subgenre',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms'],
      dtype='object')

In [5]:
cols = ['track_name', 'track_artist', 'track_album_name', 'track_album_release_date', 'playlist_name', 'playlist_id', 'playlist_genre']

In [6]:
df['track_album_name'].value_counts().head()

track_album_name
Greatest Hits                  139
Ultimate Freestyle Mega Mix     42
Gold                            35
Malibu                          30
Rock & Rios (Remastered)        29
Name: count, dtype: int64

In [7]:
df[cols].head()

,track_name,track_artist,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre
0,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop
1,Memories - Dillon Francis Remix,Maroon 5,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop
2,All the Time - Don Diablo Remix,Zara Larsson,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop
3,Call You Mine - Keanu Silva Remix,The Chainsmokers,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop
4,Someone You Loved - Future Humans Remix,Lewis Capaldi,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop

In [8]:
df = pd.read_csv('spotify_tracks.csv')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6300 entries, 0 to 6299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           6300 non-null   object
 1   name         6300 non-null   object
 2   genre        6300 non-null   object
 3   artists      6300 non-null   object
 4   album        6300 non-null   object
 5   popularity   6300 non-null   int64
 6   duration_ms  6300 non-null   int64
 7   explicit     6300 non-null   bool
dtypes: bool(1), int64(2), object(5)
memory usage: 350.8+ KB

In [10]:
df.head()

,id,name,genre,artists,album,popularity,duration_ms,explicit
0,7kr3xZk4yb3YSZ4VFtg2Qt,Acoustic,acoustic,Billy Raffoul,1975,58,172199,False
1,1kJygfS4eoVziBBI93MSYp,Acoustic,acoustic,Billy Raffoul,A Few More Hours at YYZ,57,172202,False
2,6lynns69p4zTCRxmmiSY1x,Here Comes the Sun - Acoustic,acoustic,"Molly Hocking, Bailey Rushlow",Here Comes the Sun (Acoustic),42,144786,False
3,1RC9slv335IfLce5vt9KTW,Acoustic #3,acoustic,The Goo Goo Dolls,Dizzy up the Girl,46,116573,False
4,5o9L8xBuILoVjLECSBi7Vo,My Love Mine All Mine - Acoustic Instrumental,acoustic,"Guus Dielissen, Casper Esmann",My Love Mine All Mine (Acoustic Instrumental),33,133922,False

In [11]:
df['album'].value_counts()

album
Bach & Friends                                         20
Organic Passion                                        18
Face For The Radio/Voice For A Silent Film (Deluxe)    17
Detroit Afterparty                                     16
100 Greatest Bluegrass Hits                            15
                                                       ..
Groove Window                                           1
Check Your Head (Deluxe Edition/Remastered/2009)        1
Guy                                                     1
The Essential Isley Brothers                            1
World Party 5 by Putumayo                               1
Name: count, Length: 4949, dtype: int64

In [12]:
top_albums = df['album'].value_counts().head(10).index
df[df['album'].isin(top_albums)].head()

,id,name,genre,artists,album,popularity,duration_ms,explicit
354,6O4Ad3jqaWu1jPJRu5SlXj,Foggy Mountain Breakdown,bluegrass,Joe Maphis,100 Greatest Bluegrass Hits,29,133000,False
356,135azaYAe8sbyLk54e8wON,Blue Ridge Mountain Blues,bluegrass,Patty Stoneman,100 Greatest Bluegrass Hits,18,122960,False
359,5X03JHMM85JPUlmbW4CovB,Tramp on the Street,bluegrass,Betty Jean Robinson,100 Greatest Bluegrass Hits,27,228173,False
361,6ZbB8z8u7mY40Ap3hsBMqi,Uncle Penn,bluegrass,Rose Lee Maphis,100 Greatest Bluegrass Hits,26,135066,False
363,1qS8s2xcuMf2u1TtD72PvD,Earl's Breakdown,bluegrass,Josh Graves,100 Greatest Bluegrass Hits,19,128266,False

In [13]:
df[df['album'].isin(top_albums)]['genre'].value_counts()

genre
chicago-house        18
pop-film             17
progressive-house    16
bluegrass            15
french               15
cantopop             13
post-dubstep         12
chill                10
garage               10
techno               10
piano                 5
Name: count, dtype: int64

In [14]:
df = df[df['album'].isin(top_albums)].groupby('genre').head(3)

In [15]:
df.reset_index(drop=True, inplace=True)
df['id'] = df.index
df = df.rename(columns={'id': 'sid'})

In [16]:
df

,sid,name,genre,artists,album,popularity,duration_ms,explicit
0,0,Foggy Mountain Breakdown,bluegrass,Joe Maphis,100 Greatest Bluegrass Hits,29,133000,False
1,1,Blue Ridge Mountain Blues,bluegrass,Patty Stoneman,100 Greatest Bluegrass Hits,18,122960,False
2,2,Tramp on the Street,bluegrass,Betty Jean Robinson,100 Greatest Bluegrass Hits,27,228173,False
3,3,祇想一生跟你走,cantopop,Jacky Cheung,Cantopop,6,311800,False
4,4,可一可再,cantopop,"Eason Chan, eason and the duo band",Cantopop,2,287573,False
5,5,天堂的花火,cantopop,Alan Tam,Cantopop,2,214312,False
6,6,Power Flexible,chicago-house,Chicago House Selection,Organic Passion,0,167680,False
7,7,Dancefloor Upbeat,chicago-house,Chicago House Selection,Organic Passion,0,175281,False
8,8,Basement Synth,chicago-house,Chicago House Selection,Organic Passion,0,186697,False
9,9,Chill,chill,Ka$hhh,Chill,39,108000,False
10,10,Chill,chill,"DJ Noiz, Donell Lewis, Konecs, Cessmun",Chill,43,159807,False
11,11,Chill,chill,Bakar,Chill,37,223293,False
12,12,"French Suite No. 5 in G Major, BWV 816: II. Co...",french,"Johann Sebastian Bach, Angela Hewitt",Bach & Friends,19,97173,False
13,13,"French Suite No. 4 in E-Flat Major, BWV 815a: ...",french,"Johann Sebastian Bach, Angela Hewitt",Bach & Friends,17,62640,False
14,14,"French Overture (Partita), BWV 831: III. Gavot...",french,"Johann Sebastian Bach, Angela Hewitt",Bach & Friends,17,83253,False
15,15,Garage,garage,"El Ray, Skrizzly Adams",Garage,26,139818,False
16,16,Garage,garage,LarryBurdd,Garage,22,155876,True
17,17,Garage,garage,Big Smack,Garage,14,214218,False
18,18,"Piano Sonata No. 16 in C Major, K. 545 ""Sonata...",piano,"Wolfgang Amadeus Mozart, Marc-André Hamelin",Bach & Friends,18,95520,False
19,19,"Piano Sonata No. 12 in A-Flat Major, Op. 26: I...",piano,"Ludwig van Beethoven, Angela Hewitt",Bach & Friends,17,72920,False
20,20,"Piano Sonata No. 2 in B-Flat Minor, Op. 35 ""Fu...",piano,"Frédéric Chopin, Marc-André Hamelin",Bach & Friends,16,104933,False
21,21,Guestlist'r,pop-film,poptropicaslutz!,Face For The Radio/Voice For A Silent Film (De...,30,96204,False
22,22,Clandestine Meetings,pop-film,poptropicaslutz!,Face For The Radio/Voice For A Silent Film (De...,27,136941,False
23,23,Two To Tango,pop-film,"poptropicaslutz!, aldrch",Face For The Radio/Voice For A Silent Film (De...,27,139842,False
24,24,Hero,post-dubstep,Extreme Music,Post Dubstep,21,239413,False
25,25,Fade Away,post-dubstep,Extreme Music,Post Dubstep,13,229386,False
26,26,Let It Roll,post-dubstep,Extreme Music,Post Dubstep,3,184981,False
27,27,Experience Hot,progressive-house,Progressive House Sessions,Detroit Afterparty,0,163866,False
28,28,Terrace Record,progressive-house,Progressive House Sessions,Detroit Afterparty,0,196231,False
29,29,Warehouse Flying,progressive-house,Progressive House Sessions,Detroit Afterparty,0,182909,False
30,30,Techno,techno,EzeBoss,Techno,30,69600,False
31,31,Techno,techno,Destructo,Techno,33,225306,False
32,32,Techno,techno,Dimension,Techno,33,263793,False

In [17]:
Song = df[['sid','name', 'duration_ms', 'popularity']].reset_index(drop=True)

In [18]:
Song.head()

   sid                       name  duration_ms  popularity
0    0   Foggy Mountain Breakdown       133000          29
1    1  Blue Ridge Mountain Blues       122960          18
2    2        Tramp on the Street       228173          27
3    3                    祇想一生跟你走       311800           6
4    4                       可一可再       287573           2

In [19]:
Genre = df.groupby('genre')['popularity'].mean().reset_index()
Genre['genre_id'] = range(len(Genre))
Genre

                genre  popularity  genre_id
0           bluegrass   24.666667         0
1            cantopop    3.333333         1
2       chicago-house    0.000000         2
3               chill   39.666667         3
4              french   17.666667         4
5              garage   20.666667         5
6               piano   17.000000         6
7            pop-film   28.000000         7
8        post-dubstep   12.333333         8
9   progressive-house    0.000000         9
10             techno   32.000000        10

In [20]:
SongGenre = df.merge(Genre, on = 'genre', how = 'left')[['sid', 'genre_id']]
SongGenre

    sid  genre_id
0     0         0
1     1         0
2     2         0
3     3         1
4     4         1
5     5         1
6     6         2
7     7         2
8     8         2
9     9         3
10   10         3
11   11         3
12   12         4
13   13         4
14   14         4
15   15         5
16   16         5
17   17         5
18   18         6
19   19         6
20   20         6
21   21         7
22   22         7
23   23         7
24   24         8
25   25         8
26   26         8
27   27         9
28   28         9
29   29         9
30   30        10
31   31        10
32   32        10

In [21]:
# Separate comma-separated artists for each
df['artist'] = df['artists'].str.split(",")
Sings = df.explode('artist').reset_index(drop=True)

In [22]:
# Assume artist names are unique
Artist = Sings['artist'].drop_duplicates().reset_index(drop=True).reset_index().rename(columns={'index': 'aid'})
Artist.head()

   aid               artist
0    0           Joe Maphis
1    1       Patty Stoneman
2    2  Betty Jean Robinson
3    3         Jacky Cheung
4    4           Eason Chan

In [23]:
Sings = Sings.merge(Artist, on='artist', how='left')
Sings = Sings[['aid', 'sid']]

In [24]:
Sings

    aid  sid
0     0    0
1     1    1
2     2    2
3     3    3
4     4    4
5     5    4
6     6    5
7     7    6
8     7    7
9     7    8
10    8    9
11    9   10
12   10   10
13   11   10
14   12   10
15   13   11
16   14   12
17   15   12
18   14   13
19   15   13
20   14   14
21   15   14
22   16   15
23   17   15
24   18   16
25   19   17
26   20   18
27   21   18
28   22   19
29   15   19
30   23   20
31   21   20
32   24   21
33   24   22
34   24   23
35   25   23
36   26   24
37   26   25
38   26   26
39   27   27
40   27   28
41   27   29
42   28   30
43   29   31
44   30   32

In [25]:
cleaned_album = pd.read_csv("cleaned_album.csv")[['sid','album_name','production_company','release_year']]

In [26]:
Company = cleaned_album['production_company'].dropna().drop_duplicates().reset_index(drop=True).reset_index().rename(columns = {'index':'cid'})

In [27]:
Company

   cid                 production_company
0    0            Melody Mountain Records
1    1                     Eas Music Ltd.
2    2                           Hyperion
3    3                            Epitaph
4    4  The Extreme Music Library Limited

In [28]:
cleaned_album = cleaned_album.merge(Company, on='production_company', how='left').dropna(subset='album_name')

In [29]:
Album = cleaned_album[['cid','album_name','release_year']]

In [30]:
Album

    cid                                         album_name  release_year
2   0.0                                   Bluegrass Gospel        1991.0
4   1.0                                           L.O.V.E.        2018.0
12  2.0                                  The French Suites        1995.0
13  2.0                                  The French Suites        1995.0
14  2.0                                  The French Suites        1995.0
18  2.0                              Mozart: Piano Sonatas        2015.0
19  2.0                    Beethoven: Piano Sonatas Vol. 3        2010.0
20  2.0                   Chopin: Piano Sonatas Nos. 2 & 3        2009.0
21  3.0  Face For The Radio/Voice For A Silent Film (De...        2024.0
22  3.0  Face For The Radio/Voice For A Silent Film (De...        2024.0
23  3.0  Face For The Radio/Voice For A Silent Film (De...        2024.0
24  4.0                                       Post Dubstep        2015.0
25  4.0                                       Post Dubstep        2015.0
26  4.0                                       Post Dubstep        2015.0

In [36]:
AlbumSong = cleaned_album[['sid','album_name','cid']]

In [31]:
AlbumArtist = df.merge(Sings, on='sid', how='left').merge(cleaned_album, on='sid', how='left')[['album_name', 'aid', 'cid']]

In [32]:
AlbumArtist = AlbumArtist.dropna(subset='album_name').drop_duplicates()

In [33]:
AlbumArtist

                                           album_name  aid  cid
2                                    Bluegrass Gospel    2  0.0
4                                            L.O.V.E.    4  1.0
5                                            L.O.V.E.    5  1.0
16                                  The French Suites   14  2.0
17                                  The French Suites   15  2.0
26                              Mozart: Piano Sonatas   20  2.0
27                              Mozart: Piano Sonatas   21  2.0
28                    Beethoven: Piano Sonatas Vol. 3   22  2.0
29                    Beethoven: Piano Sonatas Vol. 3   15  2.0
30                   Chopin: Piano Sonatas Nos. 2 & 3   23  2.0
31                   Chopin: Piano Sonatas Nos. 2 & 3   21  2.0
32  Face For The Radio/Voice For A Silent Film (De...   24  3.0
35  Face For The Radio/Voice For A Silent Film (De...   25  3.0
36                                       Post Dubstep   26  4.0

In [50]:
Artist.to_csv('data/Artist.txt',index=False)

In [51]:
Song.to_csv("data/Song.txt",index=False)

In [52]:
Sings.to_csv('data/Sings.txt',index=False)

In [53]:
Genre.to_csv('data/Genre.txt',index=False)

In [54]:
SongGenre.to_csv('data/SongGenre.txt',index=False)

In [55]:
Company.to_csv('data/Company.txt',index=False)

In [56]:
Album.to_csv('data/Album.txt',index=False)

In [57]:
AlbumSong.to_csv('data/AlbumSong.txt',index=False)

In [58]:
AlbumArtist.to_csv('data/AlbumArtist.txt',index=False)